### ISSUE TITLE
Use Cases 10-19

### ISSUE THREAD

**Issue by tomnisim** [tomnisim/ScooterGotcha#4]

**Comment by amitmosk** [comment]
1. Expand tables according to test scenarios

3. Separate USE Case 10 into smaller parts - the camera takes a picture and sends it to the Raspberry Pi -> the Raspberry Pi processes the image and outputs-> outputting 

3. Generate Use Cases:
- 8 into Begin ride
- 10,11,12,13 into Ridding
- 14,15 End of ride - add sending data to server
